### ISSUE TITLE
A little confusion

### ISSUE THREAD

**Issue by TonyApril** [jannisborn/covid19_pocus_ultrasound#42]
It's said that Covid-19 belongs to one kind of viral pneumonia. So I am a little confused about the difference between class Covid-19 and class pneumonia in the classification. It seems that the paper hasn't talk about it.

**Comment by jannisborn** [comment]
Dear Tony,
Thanks for your interest. I think the paper does talk about it, I'm quoting from the abstract below:
```
First, we gather a lung ultrasound (POCUS) dataset consisting of (currently) 1103 images 
(654 COVID-19, 277 bacterial pneumonia and 172 healthy controls), sampled from 64 videos.
``` 
Hence, pneumonia is short for forms of bacterial pneumonia. However, the dataset grew significantly since we put that manuscript out. Please follow the READMEs of this repo, especially the one on [`data\`](https://github.com/jannisborn/covid19_pocus_ultrasound/tree/master/data). The dataset sizes are much bigger now than what we report in the initial manuscript. Plus, we now also have a couple of videos from non-covid-viral-pneumonia, so if you want, you can include a 4-th class into your model.

**Comment by TonyApril** [comment]
Got it, thanks!

**Comment by jannisborn** [comment]
I close this issue then, please feel free to re-open if applicable.

**Comment by TonyApril** [comment]
OK




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jannis Born"<notifications@github.com&gt;; 
发送时间: 2020年7月10日(星期五) 下午3:22
收件人: "jannisborn/covid19_pocus_ultrasound"<covid19_pocus_ultrasound@noreply.github.com&gt;; 
抄送: "WRX"<907932614@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jannisborn/covid19_pocus_ultrasound] A little confusion (#42)





 
I close this issue then, please feel free to re-open if applicable.
